#!/bin/bash

n="Archstall"
echo "[$n] Start"

##[E] Check If is EFI and if not 
[ -d "/sys/firmware/efi/efivars" ] && echo "[$n] You are in efi mode. Please change it to standard."

##Setup Keyboard
####loadkeys pl

##Setup Time
####timedatectl set-ntp true


##Setup Partitions
ii=0
for i in $(fdisk -l | grep "Disk /dev" | sed "s/ /\^/g;s/://;s/,//") ; do

    echo "$ii $i" | sed 's/\^/ /g' | cut -d" " -f 1,3,4,5
    ii=$(($ii+1))

done


echo "[$n] End"

