#!/bin/bash

n="Archstall"
printf "Do you wont to start $n (yes/no) "
read out
[ $out != "yes" ] && exit

echo "[$n] Start"

##[E] Check If is EFI and if not 
[ -d "/sys/firmware/efi/efivars" ] && echo "[$n] You are in efi mode. Please change it to standard."

##Setup Keyboard
loadkeys pl

##Setup Time
timedatectl set-ntp true


##Setup Partitions ########################
ii=-1
for i in $(fdisk -l | grep "Disk /dev" | sed "s/ /\^/g;s/://;s/,//") ; do
    ii=$(($ii+1))
    echo "$ii $i" | sed 's/\^/ /g' | cut -d" " -f 1,3,4,5
done
printf "Disk [0-$ii] "
read id

disk=""
pm=0
pe=0

ii=-1
for i in $(fdisk -l | grep "Disk /dev" | sed "s/ /\^/g;s/://;s/,//") ; do
    ii=$(($ii+1))
    if [ $ii = $id ]; then 
        disk=$(printf "$i" | sed 's/\^/ /g' | cut -d" " -f 2)
        pe=$(( $(printf "$i" | sed 's/\^/ /g' | cut -d" " -f 5) /1024-4096 ))
        ps=$(( $(cat /proc/meminfo | grep "MemTotal" | sed "s/ \+/ /g" | cut -d" " -f 2) ))
        pm=$(( $pe - $ps))
    fi
done

echo "$disk $pm $pe $(( ($pe+1024) - ($pe%1024) ))"

umount $disk
sfdisk --delete $disk
s=$((2048*2))
e=$(($pm*2))
echo "1 $s $e $(( $e - $s ))"
parted $disk mkpart ext4 ${s}s ${e}s
s=$((  ( ($pm+2048) - (($pm+2048)%1024) )   *2   ))
e=$((($pe+2048)*2))
echo "2 $s $e $(( $e - $s ))"
parted $disk mkpart linux-swap ${s}s ${e}s

mkfs.ext4 ${disk}1
mkswap ${disk}2
###########################################

mount ${disk}1 /mnt
swapon ${disk}2

#Installation
pacstrap /mnt base linux linux-firmware

#Generate fstab
genfstab -U /mnt >> /mnt/etc/fstab

#Chroot 
arch-chroot /mnt

ln -sf /usr/share/zoneinfo/Europe/Warsaw /etc/localtime
hwclock --systohc

printf "en_US.UTF-8 UTF-8" >> /etc/locale.gen
printf "LANG=en_US.UTF-8" >> /etc/locale.conf
printf "KEYMAP=pl" >> /etc/vconsole.conf

printf "Hostname: "
read hn
printf "$hn" >> /etc/hostname
printf "127.0.0.1   $hn\n::1        $hn\n127.0.1.1  $hn.localdomain $hn" >> /etc/hosts

mkinitcpio -P

passwd

echo "[$n] End"

